---
- hosts: docker
#  gather_facts: no
  tasks:


  - name: Create container
    docker_container:
     name: docker-test
    # docker_host: "tcp://localhost:22"
     image: docker-test:latest
     command: bash
     detach: true
     interactive: true
     tty: true
    # tls_hostname: localhost
     tls_verify: yes

  - name: add docker container to inventory
    add_host:
       name: ansible-test
       ansible_connection: docker

- hosts: ansible-test
  gather_facts: false
  tasks:

    - name: update apt cache
      delegate_to: ansible-test
      raw: apt -y update

    - name: install python
      delegate_to: ansible-test
      raw: apt -y install python-minimal

    - name: demonstrate that normal ansible modules work
      file:
        path: /etc/testdir
        state: directory

